inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8081
metrics_address=http://0.0.0.0:8082
model_store=/home/ingon/AR_book/AnimatedDrawings/torchserve/model-store
load_models=all
disable_token_authorization=true
enable_envvars_config=true
